In [1]:
print("hello world")

hello world


In [2]:
!pip3 install numpy

In [3]:
##We are going to learn numpy now!

In [4]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
brr=np.array([1,2,3])
#creating 1D array
# creating 2D numpy array

In [6]:
print("Type of arr",type(arr))
print("Type of brr",type(brr))

Type of arr <class 'numpy.ndarray'>
Type of brr <class 'numpy.ndarray'>


In [7]:
print("Dimension of the 2D array: ",arr.ndim)
print("Dimension of the 1D array: ",brr.ndim)
#dimendion of the numpy array

Dimension of the 2D array:  2
Dimension of the 1D array:  1


In [8]:
print("shape of 2D array:",arr.shape)
print("shape of 1D array:",brr.shape)
#shape of 2D array

shape of 2D array: (2, 3)
shape of 1D array: (3,)


In [9]:
print("Size of array:",arr.size)
print("size of 1D array:",brr.size)

Size of array: 6
size of 1D array: 3


In [13]:
#printing type of element array hold'
print("type of element:",arr.dtype)

type of element: int32


In [14]:
#CREATING ARRAY IN NUMPY
#FOUR WAYS:=
#1> using list with element type
#2> using tuple
#3> using zeroes function
#4> using full function



In [16]:
# creating array from list with float values
a = np.array([[1,2,3],[5,6,7]],dtype='float')
print("array created using list:", a)

array created using list: [[1. 2. 3.]
 [5. 6. 7.]]


In [17]:
# creating array from tuple
a = np.array((1,2,3))
print("array created using tuple:",a)

array created using tuple: [1 2 3]


In [19]:
# creating a 3x4 array with zero values
a = np.zeros((3,4))
print("array with zeros:",a)

array with zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
# creating a 3x4 array with constants values
a = np.full((3,4),6,dtype='complex')
print("array with constant value 6 and type complex:",a)

array with constant value 6 and type complex: [[6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]]


In [22]:
#ones nd identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.arange?

In [29]:
#want to create a seq from 1 to 30 with steps 5
f = np.arange(1,30,5)
print(f)

[ 1  6 11 16 21 26]


In [30]:
#want to create a seq from 1 to 30 with no of values 10
f = np.linspace(1,30,10)
print(f)

[ 1.          4.22222222  7.44444444 10.66666667 13.88888889 17.11111111
 20.33333333 23.55555556 26.77777778 30.        ]


In [37]:
# random values
a = np.random.random((2))
print(a)
b = np.random.random((2,3))
print(b)

[0.38797057 0.90121166]
[[0.05309531 0.45618322 0.87553174]
 [0.75551171 0.49644213 0.42146864]]


In [42]:
# reshape the array
arr = np.array([[1,2,3,4],[5,6,7,7],[23,24,56,0]])
new_arr = arr.reshape((4,3))
print(new_arr)
new_arr = arr.reshape((2,2,3))
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  7 23]
 [24 56  0]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  7 23]
  [24 56  0]]]


In [43]:
# flattened array 
new_arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  7, 23, 24, 56,  0])

In [46]:
# SLICING AND INDEXING WORK IN NUMPY
# arr[[row:row],[col,col]]
arr =np.array([[ 1 , 2 , 3],
 [ 4 , 5 , 6],
 [ 7 , 7 ,23],
 [24 ,56 , 0]])
print(arr[0:2,0:2])


[[1 2]
 [4 5]]


In [47]:
# skiping some values
arr=np.array([[1,2,4,5],[3,4,5,6],[6,5,7,4]])
print(arr)

[[1 2 4 5]
 [3 4 5 6]
 [6 5 7 4]]


In [48]:
print(arr[0:,0::2])

[[1 4]
 [3 5]
 [6 7]]


In [51]:
print(arr[0:,1::2])

[[2 5]
 [4 6]
 [5 4]]


In [52]:
print(arr[0::2,0::2])

[[1 4]
 [6 7]]


In [53]:
#boolean array indexing
cond = arr>0
temp = arr[cond]
print("element greater than 0:",temp)

element greater than 0: [1 2 4 5 3 4 5 6 6 5 7 4]


In [56]:
# broadcasting the array
print(arr)
print(arr+1)
print(arr*2)

[[1 2 4 5]
 [3 4 5 6]
 [6 5 7 4]]
[[2 3 5 6]
 [4 5 6 7]
 [7 6 8 5]]
[[ 2  4  8 10]
 [ 6  8 10 12]
 [12 10 14  8]]


In [57]:
#taking transpose of array
print(arr.T)

[[1 3 6]
 [2 4 5]
 [4 5 7]
 [5 6 4]]


In [58]:
# function

print(arr)
print("maximum ele",arr.max())
print("maximum in particular row",arr.max(axis=1))
print("maximum in particular col",arr.max(axis=0))


[[1 2 4 5]
 [3 4 5 6]
 [6 5 7 4]]
maximum ele 7
maximum in particular row [5 6 7]
maximum in particular col [6 5 7 6]


In [59]:
#similarly min(),sum(),cumsum()

In [63]:
#BINARY OPERATIONS
atemp= np.array([[1,2],[2,3]])
btemp= np.array([[1,2],[2,3]])
#add
print(atemp+btemp)
#multiply
print(atemp*btemp)
#matrix multiplication
print(atemp.dot(btemp))

[[2 4]
 [4 6]]
[[1 4]
 [4 9]]
[[ 5  8]
 [ 8 13]]


In [66]:
print(arr)
#sort the array
print("sorting along row:",np.sort(arr,axis=1))

[[1 2 4 5]
 [3 4 5 6]
 [6 5 7 4]]
sorting along row: [[1 2 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [5]:
import numpy as np
arr=np.array([[1,2,4,5],
 [3,4,5,6],
 [6,5,7,4]])
newarr=arr.reshape(2,2,3)
print("Reshape the array",newarr)

Reshape the array [[[1 2 4]
  [5 3 4]]

 [[5 6 6]
  [5 7 4]]]


In [8]:
#stacking and splitting
a = np.array([[1,2],[3,4]])
b = np.array([[11,22],[33,44]])
print("Vertical stacking",np.vstack((a,b)))
print("Horizontal stacking",np.hstack((a,b)))
c=[5,6]
print("Column stack",np.column_stack((a,c)))
print("Concatenation to 2nd axis ",np.concatenate((a,b),1))

Vertical stacking [[ 1  2]
 [ 3  4]
 [11 22]
 [33 44]]
Horizontal stacking [[ 1  2 11 22]
 [ 3  4 33 44]]
Column stack [[1 2 5]
 [3 4 6]]
Concatenation to 2nd axis  [[ 1  2 11 22]
 [ 3  4 33 44]]


In [9]:
a = np.array([[1,2,3,7,9,11],[2,4,6,8,10,12]])

print("Splitting along horizontal axis into 2 parts:",np.hsplit(a,2))

print("Splitting along vertical axis into 2 parts:",np.vsplit(a,2))


Splitting along horizontal axis into 2 parts: [array([[1, 2, 3],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]
Splitting along vertical axis into 2 parts: [array([[ 1,  2,  3,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [10]:
#SOME MORE NUMPY FUNCTIONS - STATISTICS
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#specifying the axis
print(np.min(a,axis=0))
print(np.min(a,axis=1))


[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [13]:
#MEAN 
b = np.array([1,2,3,4,5])
n = sum(b)/5
print(n)

print(np.mean(b))
print(np.mean(b,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
3.0
[2.5  3.75]


In [15]:
#MEDIAN
c = np.array([1,5,4,2,0])
print(np.median(c))

#mean vs average is weighted
print(np.mean(c))

#weights-
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

#weighted mean => n1*w1 + n2*w2 / n1+n2

#Standard Deviation
u = np.mean(c)
myStd = np.sqrt((abs(c-u)**2))
print(myStd)

#inbuilt Function
dev = np.std(c)
print(dev)

#variance
print(myStd**2)
print(np.var(c))

2.0
2.4
2.4
[1.4 2.6 1.6 0.4 2.4]
1.854723699099141
[1.96 6.76 2.56 0.16 5.76]
3.4400000000000004


In [ ]:
#rand
#randn
#randint
#random
#choice
#shuffle